export type Trip = {
    id: string;
    driverId: string;
    riderId: string;
    driverName: string;
    riderName: string;
    date: string;
    amount: number;
    status: "completed" | "cancelled" | "ongoing";
    pickup: string;
    dropoff: string;
    distance: string;
    duration: string;
};

export const trips: Trip[] = [
    {
        id: "t1",
        driverId: "d1",
        riderId: "r1",
        driverName: "John Doe",
        riderName: "Alice Johnson",
        date: "2024-03-15T10:00:00Z",
        amount: 25.50,
        status: "completed",
        pickup: "Central Station",
        dropoff: "Airport",
        distance: "12.5 km",
        duration: "25 mins",
    },
    {
        id: "t2",
        driverId: "d2",
        riderId: "r2",
        driverName: "Jane Smith",
        riderName: "Bob Williams",
        date: "2024-03-15T11:30:00Z",
        amount: 15.00,
        status: "completed",
        pickup: "Downtown Mall",
        dropoff: "City Park",
        distance: "5.0 km",
        duration: "12 mins",
    },
    {
        id: "t3",
        driverId: "d1",
        riderId: "r3",
        driverName: "John Doe",
        riderName: "Charlie Brown",
        date: "2024-03-15T12:00:00Z",
        amount: 0.00,
        status: "cancelled",
        pickup: "123 Main St",
        dropoff: "456 Oak Ave",
        distance: "0 km",
        duration: "0 mins",
    },
    {
        id: "t4",
        driverId: "d4",
        riderId: "r4",
        driverName: "Emily Davis",
        riderName: "Diana Prince",
        date: "2024-03-15T12:15:00Z",
        amount: 45.00,
        status: "ongoing",
        pickup: "Hotel Grand",
        dropoff: "Convention Center",
        distance: "18.0 km",
        duration: "35 mins",
    },
    {
        id: "t5",
        driverId: "d5",
        riderId: "r5",
        driverName: "David Wilson",
        riderName: "Evan Wright",
        date: "2024-03-14T20:00:00Z",
        amount: 30.00,
        status: "completed",
        pickup: "Restaurant Row",
        dropoff: "Suburban Heights",
        distance: "15.0 km",
        duration: "28 mins",
    },

    // ============= NEW 5 TRIPS BELOW ============= //

    {
        id: "t6",
        driverId: "d3",
        riderId: "r6",
        driverName: "Michael Carter",
        riderName: "Sophia Lee",
        date: "2024-03-16T08:45:00Z",
        amount: 22.75,
        status: "completed",
        pickup: "City Library",
        dropoff: "Tech Park",
        distance: "10.2 km",
        duration: "22 mins",
    },
    {
        id: "t7",
        driverId: "d2",
        riderId: "r7",
        driverName: "Jane Smith",
        riderName: "Oliver Harris",
        date: "2024-03-16T09:10:00Z",
        amount: 12.00,
        status: "completed",
        pickup: "Greenwood Plaza",
        dropoff: "Rosewood Apartments",
        distance: "4.1 km",
        duration: "10 mins",
    },
    {
        id: "t8",
        driverId: "d6",
        riderId: "r8",
        driverName: "Samuel Thompson",
        riderName: "Grace Miller",
        date: "2024-03-16T10:30:00Z",
        amount: 0.00,
        status: "cancelled",
        pickup: "West End Market",
        dropoff: "Lakeside View",
        distance: "0 km",
        duration: "0 mins",
    },
    {
        id: "t9",
        driverId: "d7",
        riderId: "r9",
        driverName: "Karen White",
        riderName: "Lucas Turner",
        date: "2024-03-16T11:00:00Z",
        amount: 55.20,
        status: "completed",
        pickup: "Metro Station",
        dropoff: "Hillcrest Colony",
        distance: "20.0 km",
        duration: "40 mins",
    },
    {
        id: "t10",
        driverId: "d8",
        riderId: "r10",
        driverName: "Robert King",
        riderName: "Nora Bennett",
        date: "2024-03-16T12:20:00Z",
        amount: 38.00,
        status: "ongoing",
        pickup: "Harbor Point",
        dropoff: "Seaside Residency",
        distance: "14.3 km",
        duration: "30 mins",
    },
];
